"""
Program to generate baseline meta-predictions for the hps configurations belonging to our prior.
For a hp configuration the program computes the average z-normalized loss of the same configuration
across all datasets expect the target one. The program operates in a LODO regime.

Input: the program wants the txt files generated by the metatab program "predict_surrogate",
which contains the z-normalized loss for one classifier for all the datasets in our collection.

Output: a txt file that mirror the input with the dataset, real loss and the new computed one.
"""
# before importing metatab
import os
os.environ["SCIPY_ARRAY_API"] = "1"

import sys
import argparse
import numpy as np
import pandas as pd
from metatab.cli.helper import create_logger


def parse_args(args):
    p = argparse.ArgumentParser()
    p.add_argument("--classifier-prior", required=True,
                   help="File generated by the 'predict_surrogate' program with the optimization prior info for a classifier on all datasets")
    p.add_argument("--dataset-column", default="dataset", help="Name of the column with the dataset info.")
    p.add_argument("--loss-column", default="actual", help="Column with the z-normalized loss info.")
    p.add_argument("--remove-dataset-number-hps", type=int, default=1500, help="Remove datasets with number of hps different from the threshold.")
    p.add_argument("--output-file", required=True, help="Output filepath.")
    return p.parse_args(args)



def main():
    pars = vars(parse_args(sys.argv[1:]))
    logger = create_logger(sys.stdout)
    loss_column = pars["loss_column"]
    dataset_column = pars["dataset_column"]
    number_hps = pars["remove_dataset_number_hps"]
    prior = pd.read_csv(pars["classifier_prior"], sep="\t")
    datasets = prior[dataset_column].unique().tolist()

    # split by dataset and remove eligible datasets
    prior_datasets = {}
    for d in datasets:
        dataset_prior = prior.loc[prior[dataset_column] == d, :]
        if dataset_prior.shape[0] == number_hps:
            prior_datasets[d] = dataset_prior
        else:
            logger.debug(f"Removed '{d}' with number hps != '{number_hps}'")

    ## lodo average
    lodo_average = []
    for test_dataset in prior_datasets.keys():
        remaining = [df for d, df in prior_datasets.items() if d != test_dataset]
        loss_matrix = np.column_stack([df[loss_column].to_numpy() for df in remaining])
        avg_landscape = loss_matrix.mean(axis=1)
        actual_landscape = prior_datasets[test_dataset][loss_column].to_numpy()
        dataset_df = pd.DataFrame({
            "dataset": test_dataset,
            "actual": actual_landscape,
            "pred_average": avg_landscape,
        })
        lodo_average.append(dataset_df)
    
    df_result = pd.concat(lodo_average, axis=0, ignore_index=True)
    df_result.to_csv(pars["output_file"], sep="\t", index=False)



if __name__ == "__main__":
    main()