"""
Program to generate a forecasting learning curve on a dataset using 2 modelling approach (main + baseline).
Namely a modelling approach is an estimator plus training regime (default, (meta)tune, (meta)ensemble).
The curves are generated by splitting the data in train + test, and the train set in multiple set with 
increasing size. The models are fitted on the train set and tested on the test one.

Since the program is not intended to be used by users it misses some degree of freedom. In particular:
- we enforce a set of 2 estimators. So is not possible to perform the analysis on just 1 or more than 2.
- we enforce a fixed set of subtrain split, aka the split ratios applied to the train set.
- we use the default setting for the meta estimators in terms of candidate points and meta seed (no parameters to control this).
- we enforce the "default settings" for each regime, where for default we mean the ones explored in the original paper.
- we enforce the "df" dataset mode for loading the datasets

Note: to have full freedom one can use the metatab fit/predict API. 
In this case we must generate the datasets split beforehand. 
The we use metatab API to fit and predict calling the programs multiple times.
"""

import sys
import argparse
import numpy as np
import pandas as pd
import seaborn as sns
from typing import Literal
from pathlib import Path
from sklearn.model_selection import train_test_split
from collections import defaultdict
from metatab.cli.helper import create_logger, create_json_configuration_file
from metatab.metatab_utils.data_loader import DataLoader
from metatab.estimators.utils.pick import pick_estimator_class
from metatab.estimators.params.utils import pick_estimator_tune_space
from metatab.estimators.core.configurations import TuneConfiguration, EarlyStopConfiguration, EnsembleConfiguration
from metatab.metalearning.utils import RandomUniformFromBestMetaStrategyParams, UniformFromBestMetaStrategyParams
from metatab.estimators.utils.constants import EARLY_STOPPED_ESTIMATORS
from metatab.cli.programs.resample.helper import populate_dict_lists_
from metatab.metatab_utils.prediction.dataframe import PredictionDataframe
from metatab.estimators.utils.types import EstimatorType



def parse_args(args):
    p = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--estimator-main", required=True, help="Main estimator to use.")
    p.add_argument("--estimator-baseline", required=True, help="Estimator to use as baseline.")
    p.add_argument("--estimator-main-mode", required=True, choices=["default", "tune", "ensemble", "metatune", "metaensemble"], 
                   help="Training regime of the main estimator.")
    p.add_argument("--estimator-baseline-mode", required=True, choices=["default", "tune", "ensemble", "metatune", "metaensemble"], 
                   help="Training regime of the baseline estimator.") 
    p.add_argument("--dataset", required=True, help="Dataset filepath. Tab-separated table containing the target.")
    p.add_argument("--target-feature", required=True, help="Target column in dataset.")
    p.add_argument("--train-test-ratio", default=0.75, type=float, help="Train-test split ratio")
    p.add_argument("--subtrain-ratio", default="default", 
                   help="Ratio to use to split the train set. We enforce the default set of (0.5, 0.6, 0.7, 0.8, 0.9)")
    p.add_argument("--n-repeats", default=10, type=int, help="Number of repeats of the entire procedure")
    p.add_argument("--seed", default=0, type=int, help="Seed controlling the process randomness.")
    p.add_argument("--surrogate-model", default = None, help="Surrogate model to use. Info used only for 'meta' estimator modes.")
    p.add_argument("--threads", default=16, type=int, help="Number of threads to use to fit the estimators.")
    p.add_argument("--metric", default="auc", help="Metric on which the curves are generated.")
    p.add_argument("--output-folder", required=True, help="Folder in output.")
    return p.parse_args(args)



def build_estimator_configuration(
    estimator: EstimatorType,
    estimator_mode: Literal["default", "tune", "ensemble", "metatune", "metaensemble"],
    surrogate_model: None | str,
    output_path: Path
) -> dict:
    '''
    Helper to build the configuration needed to initilize estimators according to the regime. 
    Here we use fixed settings for each regime.
    Returns a dict to unpackage in the estimator initialization.
    '''
    tune_configuration = None
    ensemble_configuration = None
    early_stop_configuration = None

    if estimator_mode in ["tune", "metatune"]:
        tune_configuration = TuneConfiguration(
            algo="tpe" if estimator_mode == "tune" else "meta",
            n_iter=100 if estimator_mode == "tune" else 1,
            n_cv_repeats=1,
            n_cv_folds=5,
            params_distributions=pick_estimator_tune_space(estimator, "c0"),
            meta_surrogate_model=None if estimator_mode == "tune" else surrogate_model
        )
    
    elif estimator_mode in ["ensemble", "metaensemble"]:
        ensemble_configuration = EnsembleConfiguration(
            name=f"{estimator}",
            algo="random" if estimator_mode == "ensemble" else "meta",
            n_members=16,
            save_path=output_path / f"{estimator_mode}__{estimator}",
            params_distributions=pick_estimator_tune_space(estimator, "c0"),
            meta_surrogate_model=None if estimator_mode == "ensemble" else surrogate_model,
            # we use the meta-settings used in the main analysis
            meta_strategy="random_uniform_from_best",
            meta_strategy_params=RandomUniformFromBestMetaStrategyParams(n_candidate_points=1500, step_size=10)
        )

    if estimator in EARLY_STOPPED_ESTIMATORS:
        # we use the default configuration used in the main analyses
        early_stop_configuration = EarlyStopConfiguration()

    return {
        "tune_configuration": tune_configuration, 
        "ensemble_configuration": ensemble_configuration, 
        "early_stop_configuration": early_stop_configuration
    }




def main():
    pars = vars(parse_args(sys.argv[1:]))
    create_json_configuration_file(pars, pars["output_folder"])
    logger = create_logger(sys.stdout) 

    logger.info((
        f"Launching {pars["estimator_main_mode"]} {pars["estimator_main"]} (main) " 
        f"and {pars["estimator_baseline_mode"]} {pars["estimator_baseline"]} (baseline) on {pars["dataset"]}."
    ))

    output_folder = Path(pars["output_folder"])
    output_folder.mkdir(parents=True, exist_ok=True)

    dl = DataLoader()
    dl.load_df_mode(pars["dataset"], target_feature=pars["target_feature"], load_as="generic")
    X, y, dataset_name = dl.X, dl.y, dl.generic_dataset_name

    logger.info(f"Loaded {dataset_name} in memory.")

    main_estimator_class = pick_estimator_class(pars["estimator_main"], pars["estimator_main_mode"])
    baseline_estimator_class = pick_estimator_class(pars["estimator_baseline"], pars["estimator_baseline_mode"])

    main_estimator_conf = build_estimator_configuration(
        estimator=pars["estimator_main"],
        estimator_mode=pars["estimator_main_mode"],
        surrogate_model=pars["surrogate_model"],
        output_path=output_folder
    )

    baseline_estimator_conf = build_estimator_configuration(
        estimator=pars["estimator_baseline"],
        estimator_mode=pars["estimator_baseline_mode"],
        surrogate_model=pars["surrogate_model"],
        output_path=output_folder
    )

    # we fix these according to scenario
    preprocessing_main = "density_filter" if pars["estimator_main"] == "tabpfn" else "base"
    preprocessing_baseline = "density_filter" if pars["estimator_baseline"] == "tabpfn" else "base"
    device_main = "cuda" if pars["estimator_main"] in ["tabpfn", "tabm", "realmlp"] else "cpu"
    device_baseline = "cuda" if pars["estimator_baseline"] in ["tabpfn", "tabm", "realmlp"] else "cpu"

    rng = np.random.default_rng(pars["seed"])
    subratios = [0.5, 0.6, 0.7, 0.8, 0.9]

    dict_results_main = defaultdict(list)
    dict_results_baseline = defaultdict(list)


    for repeat in range(pars["n_repeats"]):
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, 
            train_size=pars["train_test_ratio"],
            random_state=rng,
            stratify=y
        )

        for subratio in subratios:
            X_train_sub, _, y_train_sub, _ = train_test_split(
                X_train, y_train,
                train_size=subratio,
                random_state=rng,
                stratify=y
            )

            sub_y_classes, sub_y_counts = np.unique(y_train_sub.to_numpy(), return_counts=True)

            main_estimator = main_estimator_class(
                preprocessing=preprocessing_main,
                seed=rng.integers(low=0, high=2**31),
                device=device_main,
                n_threads=pars["nthreads"],
                **main_estimator_conf
            )

            baseline_estimator = baseline_estimator_class(
                preprocessing=preprocessing_baseline,
                seed=rng.integers(low=0, high=2**31),
                device=device_baseline,
                n_threads=pars["nthreads"],
                **baseline_estimator_conf
            )

            main_estimator.fit(X_train_sub, y_train_sub)
            pred_proba_main = main_estimator.predict_proba(X_test)
            
            baseline_estimator.fit(X_train_sub, y_train_sub)
            pred_proba_baseline = baseline_estimator.predict_proba(X_test)

            iter_results = {
                "dataset": dataset_name,
                "predict_dataset": dataset_name,
                "repeat": repeat,
                "subratio": subratio,
                "classes": sub_y_classes,
                "classes_counts": sub_y_counts,
                "y_test": y_test
            }

            iter_results_main = {
                "estimator": pars["estimator_main"],
                "estimator_mode": pars["estimator_main_mode"],
                "pred_proba": pred_proba_main,
                "estimator_priority": "main",
                **iter_results
            }

            iter_results_baseline = {
                "estimator": pars["estimator_baseline"],
                "estimator_mode": pars["estimator_baseline_mode"],
                "pred_proba": pred_proba_baseline,
                "estimator_priority": "baseline",
                **iter_results
            }

            populate_dict_lists_(dict_results_main, **iter_results_main)
            populate_dict_lists_(dict_results_baseline, **iter_results_baseline)


    df_pred = PredictionDataframe()
    df_pred_main = df_pred.build_from_data(**dict_results_main).compute_metrics()
    df_pred_baseline = df_pred.build_from_data(**dict_results_baseline).compute_metrics()
    
    
    df_out = pd.concat([df_pred_main.get_df(), df_pred_baseline.get_df()], axis=0, ignore_index=True)
    
#     # mean lineplot 
#     sns.lineplot(
#         data=df_out,
#         x="subratio",
#         y="auc",
#         yue=""
#         estimator=np.mean,     # aggregation function
#         errorbar="sd",         # standard deviation
# )


#     # median lineplot


    
    ## do plots
    ## save all outputs
    df_pred_main.to_csv(output_folder / "pred_dataframe_main.txt")
    df_pred_baseline.to_csv(output_folder / "pred_dataframe_baseline.txt")    





if __name__ == "__main__":
    main()