from __future__ import annotations

import warnings
import pandas as pd
from typing import TYPE_CHECKING, Literal
from sklearn.utils.validation import check_is_fitted
from pytabkit import RealMLP_TD_Classifier
from metatab.estimators.params import DefaultParams, TuningParams
from metatab.estimators.core.configurations import EarlyStopConfiguration

from metatab.estimators.core import (
    AbstractBaseEstimator,
    DefaultEstimatorMixin,
    EnsembleEstimatorMixin,
    TunedEstimatorMixin,
    MetaTuneBaseEstimator,
    MetaEnsembleBaseEstimator
)

if TYPE_CHECKING:
    import numpy as np
    from metatab.metatab_utils.types import XType, YType



def suppress_realmlp_warnings(func):
    def wrapper(*args, **kwargs):
        with warnings.catch_warnings():
            warnings.filterwarnings(
                action="ignore", 
                message="'force_all_finite' was renamed to 'ensure_all_finite'.*",
                category=FutureWarning
            )
            warnings.filterwarnings(
                action="ignore",
                message="Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning`.*"
            )
            return func(*args, **kwargs)
    return wrapper



# README: 
# The interface does not follow the sklearn design using **params in init.
# For this reason we miss some sklearn features and compabilities.
# These should not be used/useful to us (the useful ones are explicitely implemented).
class RealMLPClassifier:
    '''
    Wrapper of "RealMLP_TD_Classifier" that allows for:
    1. "auto" batch size option.
    2. Suppression of undesired sklearn warnings.
    3. fit method with eval_set-like interface.
    4. learns "feature_names_in_" attribute

    Parameters:
        Accept all RealMLP_TD_Classifier parameters.
    '''
    def __init__(self, batch_size: int | Literal["auto"] = 256, **params):
        self.batch_size=batch_size
        self.params=params


    @suppress_realmlp_warnings
    def fit(self, X: XType, y: YType, eval_set: list[tuple[XType, YType]], **kwargs) -> "RealMLPClassifier":
        '''
        Fit interface accepting the X and y validation sets via "eval_set-like" parameter.
        Accepts the additional realmlp args via kwargs.

        Parameters:
            X (XType): data to fit.
            y (YType): data labels to fit.
            eval_set (list[tuple[XType, YType]]):
                List of a SINGLE binary tuple with the Xy validation sets.
                Here we use this signature to be consistent with the GBDTs
                interfaces which accept multiple (potentially) validation sets.
                Cannot be None since we do NOT want to rely on the internal automatic
                system to infer the validation sets. Infact they are always used by RealMLP_TD_Classifier.
            Kwargs:
                Additional keyword parameters accepted by the fit method of RealMLP_TD_Classifier.
                The arguments that pass/specify the validation sets must not be used in favor of
                the `eval_set` parameter.
        '''
        import logging
        from metatab.estimators.utils.general import collect_sklearn_classification_fit_info

        self.batch_size_ = self.batch_size \
            if isinstance(self.batch_size, int) \
            else self._infer_batch_size_from_data(X)
        
        X_val = eval_set[0][0]
        y_val = eval_set[0][1]
        self.classifier = RealMLP_TD_Classifier(batch_size=self.batch_size_, **self.params)

        # to get rid of the pytorch-lightning logs generated by the fit call
        # https://stackoverflow.com/questions/74364944/how-to-get-rid-of-info-logging-messages-in-pytorch-lightning 
        log = logging.getLogger("pytorch_lightning")
        log.propagate = False
        log.setLevel(logging.ERROR)
        self.classifier.fit(X, y, X_val=X_val, y_val=y_val, **kwargs)
        
        for k, v in collect_sklearn_classification_fit_info(self.classifier).items():
            setattr(self, k, v)

        # learn feature_names_in_ which is not learned by pytabkit classifiers
        if isinstance(X, pd.DataFrame) and all([isinstance(col, str) for col in X.columns]):
            self.feature_names_in_ = X.columns
        
        return self
    

    @suppress_realmlp_warnings
    def predict(self, X: XType) -> np.ndarray:
        check_is_fitted(self, "classifier")
        return self.classifier.predict(X)
    

    @suppress_realmlp_warnings
    def predict_proba(self, X: XType) -> np.ndarray:
        check_is_fitted(self, "classifier")
        return self.classifier.predict_proba(X)
    

    def set_params(self, **params) -> "RealMLPClassifier":
        if params.get("batch_size", None) is not None:
            self.batch_size = params.pop("batch_size")
        # here we must update to not lose all previous info
        self.params.update(params)
        return self
        

    def get_params(self, *args, **kwargs) -> dict:
        return {"batch_size": self.batch_size, **self.params}


    @staticmethod
    def _infer_batch_size_from_data(X: XType) -> None:
        n_samples = X.shape[0]
        if n_samples <= 256*3:
            return int(n_samples / 3)
        else:
            # the default
            return 256



class MyRealMLPClassifier(DefaultEstimatorMixin, AbstractBaseEstimator):
    '''
    Implementation of the library default RealMLPClassifier.

    Attributes:
        estimator_ (Pipeline): Fitted pipeline object.
    '''
    fixed_params = DefaultParams.REALMLP_DEFAULT_PARAMS
 
    def fit(self, X: XType, y: YType) -> "MyRealMLPClassifier":
        self.estimator_ = super().fit_estimator(
            X=X,
            y=y,
            classifier_cls=RealMLPClassifier,
            type_estimator="realmlp",
            is_early_stopped=True,
            early_stop_rounds_parameter=None, # it uses best-last-epoch selection
            n_threads_parameter="n_threads",
            device_parameter="device",
            density_feature_selector_strategy="undersample" # to speed up
        )
        return self
    


class MyTunedRealMLPClassifier(TunedEstimatorMixin, AbstractBaseEstimator):
    '''
    Implementation of the tuned RealMLPClassifier.

    Attributes:
        estimator_ (SearchCV): Fitted SearchCV object.
    '''
    fixed_params = TuningParams.REALMLP_FIXED_PARAMS

    def fit(self, X: XType, y: YType) -> "MyTunedRealMLPClassifier":
        self.estimator_ = super().fit_estimator(
            X=X,
            y=y,
            classifier_cls=RealMLPClassifier,
            type_estimator="realmlp",
            is_tuned=True,
            is_early_stopped=True,
            early_stop_rounds_parameter=None, # it uses best-last-epoch selection or adaptive patience
            n_threads_parameter="n_threads",
            device_parameter="device",
            density_feature_selector_strategy="undersample" # to speed up.
        )
        return self
    


class MyEnsembledRealMLPClassifier(EnsembleEstimatorMixin, AbstractBaseEstimator):
    '''
    Implementation of the ensembled RealMLPClassifier.

    Attributes:
        estimator_ (EnsembleEstimator): Fitted EnsembleEstimator object.
    '''
    fixed_params = TuningParams.REALMLP_FIXED_PARAMS

    def fit(self, X: XType, y: YType) -> "MyEnsembledRealMLPClassifier":
        self.estimator_ = super().fit_estimator(
            X=X,
            y=y,
            classifier_cls=RealMLPClassifier,
            type_estimator="realmlp",
            is_ensembled=True,
            is_early_stopped=True,
            early_stop_rounds_parameter=None, # it uses best-last-epoch selection or adaptive patience
            n_threads_parameter="n_threads",
            device_parameter="device",
            density_feature_selector_strategy="undersample" # to speed up.
        )
        return self
    


class MetaTuneRealMLPClassifier(MetaTuneBaseEstimator):
    def fit(self, X: XType, y: YType, validation_set_size: float = 0.3) -> "MetaTuneRealMLPClassifier":
        esc = EarlyStopConfiguration(validation_set_size=validation_set_size)
        super().fit(X, y, "base", MyTunedRealMLPClassifier, TuningParams.REALMLP_C0, esc)
        return self



class MetaEnsembleRealMLPClassifier(MetaEnsembleBaseEstimator):
    def fit(self, X: XType, y:YType, validation_set_size: float = 0.3) -> "MetaEnsembleRealMLPClassifier":
        esc = EarlyStopConfiguration(validation_set_size=validation_set_size)
        super().fit(X, y, "base", MyEnsembledRealMLPClassifier, TuningParams.REALMLP_C0, esc)
        return self