from __future__ import annotations

import logging
import warnings
import optuna
from typing import TYPE_CHECKING, Literal
from sklearn.utils.validation import check_is_fitted
from pytabkit import RealMLP_TD_Classifier
from metatab.utils.core import learn_sklearn_features_attributes, check_predict_features

if TYPE_CHECKING:
    import numpy as np
    from metatab.utils.types import XType, YType



def suppress_realmlp_warnings(func):
    def wrapper(*args, **kwargs):
        with warnings.catch_warnings():
            warnings.filterwarnings(
                action="ignore", 
                message="'force_all_finite' was renamed to 'ensure_all_finite'.*",
                category=FutureWarning
            )
            warnings.filterwarnings(
                action="ignore",
                message="Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning`.*"
            )
            return func(*args, **kwargs)
    return wrapper



# README: 
# The interface does not follow the sklearn design using **params in init.
# For this reason we miss some sklearn features and compabilities.
# These should not be used/useful to us (the useful ones are explicitely implemented).
class RealMLPClassifier:
    '''
    Wrapper of "RealMLP_TD_Classifier" that allows for:
    1. "auto" batch size option.
    2. Suppression of undesired sklearn warnings.
    3. fit method with eval_set-like interface.
    4. learns "feature_names_in_" attribute
    5. check fit features at predict level

    Parameters:
        Accept all RealMLP_TD_Classifier parameters.
    '''
    def __init__(self, batch_size: int | Literal["auto"] = 256, **params):
        self.batch_size=batch_size
        self.params=params


    @suppress_realmlp_warnings
    def fit(self, X: XType, y: YType, eval_set: list[tuple[XType, YType]], **kwargs) -> "RealMLPClassifier":
        '''
        Fit interface accepting the X and y validation sets via "eval_set-like" parameter.
        Accepts the additional realmlp args via kwargs.

        Parameters:
            X (XType): data to fit.
            y (YType): data labels to fit.
            eval_set (list[tuple[XType, YType]]):
                List of a SINGLE binary tuple with the Xy validation sets.
                Here we use this signature to be consistent with the GBDTs
                interfaces which accept multiple (potentially) validation sets.
                Cannot be None since we do NOT want to rely on the internal automatic
                system to infer the validation sets. Infact they are always used by RealMLP_TD_Classifier.
            Kwargs:
                Additional keyword parameters accepted by the fit method of RealMLP_TD_Classifier.
                The arguments that pass/specify the validation sets must not be used in favor of
                the `eval_set` parameter.
        '''
        self.batch_size_ = self.batch_size \
            if isinstance(self.batch_size, int) \
            else self._infer_batch_size_from_data(X)
        
        X_val = eval_set[0][0]
        y_val = eval_set[0][1]
        self.classifier_ = RealMLP_TD_Classifier(batch_size=self.batch_size_, **self.params)
        # to get rid of the pytorch-lightning logs generated by the fit call
        # https://stackoverflow.com/questions/74364944/how-to-get-rid-of-info-logging-messages-in-pytorch-lightning 
        log = logging.getLogger("pytorch_lightning")
        log.propagate = False
        log.setLevel(logging.ERROR)
        self.classifier_.fit(X, y, X_val=X_val, y_val=y_val, **kwargs)
        for k, v in learn_sklearn_features_attributes(X).items(): setattr(self, k, v)
        return self
    

    @suppress_realmlp_warnings
    def predict(self, X: XType) -> np.ndarray:
        check_is_fitted(self, "classifier_")
        check_predict_features(self, X)
        return self.classifier_.predict(X)
    

    @suppress_realmlp_warnings
    def predict_proba(self, X: XType) -> np.ndarray:
        check_is_fitted(self, "classifier_")
        check_predict_features(self, X)
        return self.classifier_.predict_proba(X)
    

    def set_params(self, **params) -> "RealMLPClassifier":
        if params.get("batch_size", None) is not None:
            self.batch_size = params.pop("batch_size")
        # here we must update to not lose all previous info
        self.params.update(params)
        return self
        

    def get_params(self, *args, **kwargs) -> dict:
        return {"batch_size": self.batch_size, **self.params}


    @staticmethod
    def _infer_batch_size_from_data(X: XType) -> None:
        n_samples = X.shape[0]
        if n_samples <= 256*3:
            return int(n_samples / 3)
        else:
            # the default
            return 256


def _realmlp_sampler_function(trial: optuna.Trial) -> dict:
    '''
    We use the autogluon/tabarena space with minor modifications.
    "https://github.com/autogluon/tabarena/blob/main/tabarena/tabarena/models/realmlp/generate.py"
    '''
    return {
        "batch_size": trial.suggest_categorical("batch_size", ["auto", 256]),
        "n_hidden_layers": trial.suggest_int("n_hidden_layers", 2, 4),
        "hidden_width": trial.suggest_categorical("hidden_width", [256, 384, 512]), # increase in time and memory
        "tfms": trial.suggest_categorical("tfms", [[], ["median_center", "robust_scale", "smooth_clip"]]), # none or default preprocessing
        "plr_sigma": trial.suggest_float("plr_sigma", 1e-2, 50.0, log=True),
        "plr_hidden_1": trial.suggest_categorical("plr_hidden_1", [8, 16, 32]), # have a minor-moderate impact on time and memory peak
        "plr_hidden_2": trial.suggest_categorical("plr_hidden_2", [4, 6, 8, 12]), # have a large impact on time and memory peak
        "plr_lr_factor": trial.suggest_float("plr_lr_factor", 5e-2, 3e-1, log=True),
        "p_drop": trial.suggest_float("p_drop", 0.0, 0.5),
        "scale_lr_factor": trial.suggest_float("scale_lr_factor", 2.0, 10.0, log=True),
        "first_layer_lr_factor": trial.suggest_float("first_layer_lr_factor", 0.3, 1.5, log=True),
        "lr": trial.suggest_float("lr", 2e-2, 3e-1, log=True),
        "wd": trial.suggest_float("wd", 1e-3, 5e-2, log=True),
        "use_early_stopping": trial.suggest_categorical("use_early_stopping", [False, True]), # can help in reducing computational time
        }



class RealMLPSpec:
    classifier_class = RealMLPClassifier
    early_stop_on_validation_set = True
    random_state_parameter = "random_state"
    n_threads_parameter = "n_threads"
    device_parameter = "device"
    main_device = "cuda"
    supported_devices = ["cpu", "cuda"]
    default_preprocessing = "base"
    default_params = {
        "val_metric_name": "cross_entropy",
        # is suggested by author to set label smooting to False when you are interested in AUC/log-loss
        "use_ls": False
    },
    fixed_params = {
        # we double the default of 256 since we work with small datasets and so each epoch is made of few steps
        "n_epochs": 512, # increase in time
        "val_metric_name": "cross_entropy",
        "use_ls": False,
        "n_ens": 8, # increase in time and memory peak
        "hidden_sizes": "rectangular",
        "early_stopping_additive_patience": 60 # we x3 the default of 20 to be less aggressive
    },
    callbacks_on_params = None
    sampler_function = _realmlp_sampler_function
    initialize_search_function = lambda: None
    params_as_object_columns_in_df_search = None